version: "3.3"

networks:
  private:
   ipam:
      config:
      - subnet: 172.16.238.0/24

volumes:
  client:
  server:
  mongodb:

services:
  mongodb:
    image: mongo
    volumes:
      - mongodb:/var/lib/mongodb
    ports:
      - 27017:27017
    env_file:
      - ../server/.env
    restart: always  
    networks:
      - private
  server:
    image: node:12.15.0-alpine
    depends_on:
      - "mongodb"
    networks:
      - "private"
    ports:
      - "3000:3000"
    volumes:
      - "../server/:/opt/server/"
    env_file:
      - ../server/.env_prod
    working_dir: 
      "/opt/server"      
    command: "npm run start:prod"
    restart: "unless-stopped"
  client:
    image: node:12.15.0-alpine
    depends_on:
      - "server"
    networks:
      - "private"
    ports:
      - "4000:4000"
    volumes:
      - "../client/:/opt/client/"
    working_dir: 
      "/opt/client"      
    command: "npm run start:prod"
    restart: "unless-stopped"
