version: "3.3"

networks:
  private:
   ipam:
      config:
      - subnet: 172.16.238.0/24

volumes:
  mongodb:

services:
  mongodb:
    image: mongo
    volumes:
      - mongodb:/var/lib/mongodb
    ports:
      - 27017:27017
    env_file:
      - ../server/.env
    restart: always  
    networks:
      - private